In [1]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
A= np.array(a)
print(a)
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
A.ndim

2

In [3]:
a.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [4]:
A.shape

(3, 3)

In [5]:
A.size

9

In [6]:
A[0,2]

3

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
A[3,1]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [9]:
A[0,0:2]

array([1, 2])

In [11]:
A[0:2,2]

array([3, 6])

In [12]:
A[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [13]:
X = np.array([[11,12,13],[21,22,23],[31,32,33]])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)
print(Y)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
X= X +Y

In [15]:
print(X)

[[12 14 16]
 [25 27 29]
 [38 40 42]]


In [18]:
print(2*X)
print(X)

[[24 28 32]
 [50 54 58]
 [76 80 84]]
[[12 14 16]
 [25 27 29]
 [38 40 42]]


In [21]:
M = np.array([[0,1,1],[1,0,1]])
N = np.array([[1,1],[1,1],[-1,1]])
print(M)
print(N)
print(np.dot(M,N))

[[0 1 1]
 [1 0 1]]
[[ 1  1]
 [ 1  1]
 [-1  1]]
[[0 2]
 [0 2]]


In [22]:
print(np.dot(N,M))

[[ 1  1  2]
 [ 1  1  2]
 [ 1 -1  0]]


In [23]:
a= np.array([0,1])
b= np.array([1,0])

In [24]:
print(np.dot(a,b))

0
